<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Contact;
use App\Models\Reminder;
use App\Models\User;


class ReminderTestSeeder extends Seeder
{
    public function run(): void
    {
        // 1. Fetch all contacts generated by ContactSeeder
        $contacts = Contact::all();

        if ($contacts->isEmpty()) {
            $this->command->warn('No contacts found. Run ContactSeeder first.');
            return;
        }

        // 2. Take a small handful of contacts to hook test reminders to
        // We limit it so your database doesn't bloat with millions of reminders
        $sampleContacts = $contacts->take(50);

        $sampleContacts->each(function ($contact) {
            
            // Reminder 1: Due Today
            Reminder::create([
                'contact_id'  => $contact->id,
                'title'       => 'Follow up with ' . $contact->name . ' today',
                'description' => 'Discuss the latest price quote update.',
                'due_date'    => today(),
                'completed'   => false,
            ]);

            // Reminder 2: Future Reminder (Due in 3 Days)
            Reminder::create([
                'contact_id'  => $contact->id,
                'title'       => 'Send proposal update to ' . $contact->name,
                'description' => 'Check in regarding the project draft contract.',
                'due_date'    => today()->addDays(3),
                'completed'   => false,
            ]);

            // Reminder 3: An Overdue Reminder (Due 2 Days Ago)
            Reminder::create([
                'contact_id'  => $contact->id,
                'title'       => 'Review discovery call logs for ' . $contact->name,
                'description' => 'Past due priority check-in.',
                'due_date'    => today()->subDays(2),
                'completed'   => false,
            ]);
            
        });

        $this->command->info('Reminders (Today, Future, and Overdue) seeded successfully matching existing contact owners.');
    }
}
